Repository Orbital-ARMazing/Orbital-ARMazing, pull requests merged in 2022-06, with the labels that each got.

#17 Role-based access control and Events joining
  Web/jsconfig.json
  Web/package-lock.json
  Web/package.json
  Web/prisma/schema.prisma
  Web/src/components/Auth.js
  Web/src/components/Card.js
  Web/src/components/Sidebar.js
  Web/src/components/UserProfile.js
  Web/src/constants/admin.js
  Web/src/constants/helper.js
  Web/src/helper/asset.js
  Web/src/helper/dashboard.js
  Web/src/helper/db.js
  Web/src/helper/event.js
  Web/src/helper/session.js
  Web/src/helper/user.js
  Web/src/pages/api/asset/create.js
  Web/src/pages/api/asset/fetch.js
  Web/src/pages/api/auth/[...nextauth].js
  Web/src/pages/api/dashboard/statistic.js
  Web/src/pages/api/event/create.js
  Web/src/pages/api/event/fetch.js
  Web/src/pages/api/event/join.js
  Web/src/pages/asset.js
  Web/src/pages/event.js
  Web/src/pages/index.js
Labels: enhancement

#22 Implemented ESLint: AirBNB and Linting fixes
  Web/.eslintrc.json
  Web/.husky/pre-commit
  Web/.prettierrc.json
  Web/package-lock.json
  Web/package.json
  Web/src/components/Auth.js
  Web/src/components/Auth.jsx
  Web/src/components/Card.js
  Web/src/components/Card.jsx
  Web/src/components/Header.js
  Web/src/components/Header.jsx
  Web/src/components/Loading.js
  Web/src/components/Loading.jsx
  Web/src/components/NavLink.js
  Web/src/components/NavLink.jsx
  Web/src/components/Sidebar.js
  Web/src/components/Sidebar.jsx
  Web/src/components/TableWidget.js
  Web/src/components/TableWidget.jsx
  Web/src/components/UserProfile.js
  Web/src/components/UserProfile.jsx
  Web/src/constants/helper.js
  Web/src/constants/months.js
  Web/src/constants/weekdays.js
  Web/src/helper/asset.js
  Web/src/helper/dashboard.js
  Web/src/helper/db.js
  Web/src/helper/event.js
  Web/src/helper/quiz.js
  Web/src/helper/session.js
  Web/src/helper/user.js
  Web/src/layout/Loading.js
  Web/src/layout/Loading.jsx
  Web/src/layout/index.jsx
  Web/src/pages/_app.js
  Web/src/pages/_app.jsx
  Web/src/pages/api/asset/create.js
  Web/src/pages/api/asset/fetch.js
  Web/src/pages/api/auth/[...nextauth].js
  Web/src/pages/api/dashboard/statistic.js
  Web/src/pages/api/event/create.js
  Web/src/pages/api/event/fetch.js
  Web/src/pages/api/event/join.js
  Web/src/pages/api/quiz/create.js
  Web/src/pages/api/quiz/fetch.js
  Web/src/pages/asset.jsx
  Web/src/pages/event.jsx
  Web/src/pages/index.jsx
  Web/src/pages/quiz.jsx
  Web/src/pages/signin.js
  Web/src/pages/signin.jsx
  Web/src/pages/unauthorized.js
  Web/src/pages/unauthorized.jsx
Labels: enhancement

#29 TypeScript Integration
  Web/.eslintrc.json
  Web/README.md
  Web/jsconfig.json
  Web/motion.ts
  Web/next-env.d.ts
  Web/package-lock.json
  Web/package.json
  Web/src/components/Auth.tsx
  Web/src/components/Card.tsx
  Web/src/components/Header.tsx
  Web/src/components/Loading.tsx
  Web/src/components/NavLink.tsx
  Web/src/components/Sidebar.tsx
  Web/src/components/TableWidget.tsx
  Web/src/components/UserProfile.tsx
  Web/src/constants/admin.ts
  Web/src/constants/helper.ts
  Web/src/constants/months.ts
  Web/src/constants/weekdays.ts
  Web/src/helper/asset.ts
  Web/src/helper/dashboard.ts
  Web/src/helper/db.ts
  Web/src/helper/event.ts
  Web/src/helper/quiz.ts
  Web/src/helper/session.ts
  Web/src/helper/user.ts
  Web/src/layout/Loading.tsx
  Web/src/layout/index.tsx
  Web/src/pages/_app.tsx
  Web/src/pages/api/asset/create.ts
  Web/src/pages/api/asset/fetch.ts
  Web/src/pages/api/auth/[...nextauth].ts
  Web/src/pages/api/dashboard/statistic.ts
  Web/src/pages/api/event/create.ts
  Web/src/pages/api/event/fetch.ts
  Web/src/pages/api/event/join.ts
  Web/src/pages/api/quiz/create.ts
  Web/src/pages/api/quiz/fetch.ts
  Web/src/pages/asset.tsx
  Web/src/pages/event.tsx
  Web/src/pages/index.tsx
  Web/src/pages/quiz.tsx
  Web/src/pages/signin.tsx
  Web/src/pages/unauthorized.tsx
  Web/src/types/api.ts
  Web/src/types/asset.ts
  Web/src/types/auth.ts
  Web/src/types/dashboard.ts
  Web/src/types/event.ts
  Web/src/types/quiz.ts
  Web/tsconfig.json
Labels: enhancement

#30 API for Unity + TypeScript types
  .github/workflows/build.yml
  Web/.husky/pre-commit
  Web/Procfile
  Web/jsconfig.json
  Web/package.json
  Web/src/components/Auth.tsx
  Web/src/components/TableWidget.tsx
  Web/src/components/UserProfile.tsx
  Web/src/constants/helper.ts
  Web/src/constants/months.ts
  Web/src/helper/asset.ts
  Web/src/helper/event.ts
  Web/src/helper/quiz.ts
  Web/src/helper/session.ts
  Web/src/helper/user.ts
  Web/src/layout/index.tsx
  Web/src/pages/api/asset/fetch.ts
  Web/src/pages/api/event/create.ts
  Web/src/pages/api/event/fetch.ts
  Web/src/pages/api/quiz/fetch.ts
  Web/src/pages/api/unity/asset.ts
  Web/src/pages/api/unity/event.ts
  Web/src/pages/api/unity/quiz.ts
  Web/src/pages/asset.tsx
  Web/src/pages/event.tsx
  Web/src/pages/index.tsx
  Web/src/pages/quiz.tsx
  Web/src/pages/signin.tsx
  Web/src/types/api.ts
  Web/src/types/event.ts
  Web/src/types/next-auth.d.ts
Labels: enhancement

#33 Leaderboard + Ranking
  Web/package-lock.json
  Web/package.json
  Web/prisma/schema.prisma
  Web/public/assets/cl3i83aw900002wdrvzk4kv5a_museum.png
  Web/public/assets/cl3i83aw900002wdrvzk4kv5a_sheares.png
  Web/public/assets/cl4b9auoo0018icdrn9aq2t8a_keviibear.png
  Web/src/components/Sidebar.tsx
  Web/src/helper/asset.ts
  Web/src/helper/dashboard.ts
  Web/src/helper/event.ts
  Web/src/helper/leaderboard.ts
  Web/src/helper/quiz.ts
  Web/src/helper/user.ts
  Web/src/pages/api/asset/fetch.ts
  Web/src/pages/api/event/create.ts
  Web/src/pages/api/event/fetch.ts
  Web/src/pages/api/event/join.ts
  Web/src/pages/api/leaderboard/fetch.ts
  Web/src/pages/api/quiz/create.ts
  Web/src/pages/api/quiz/fetch.ts
  Web/src/pages/api/unity/asset.ts
  Web/src/pages/api/unity/event.ts
  Web/src/pages/api/unity/join.ts
  Web/src/pages/api/unity/leaderboard.ts
  Web/src/pages/api/unity/points.ts
  Web/src/pages/api/unity/quiz.ts
  Web/src/pages/asset.tsx
  Web/src/pages/event.tsx
  Web/src/pages/leaderboard.tsx
  Web/src/pages/quiz.tsx
  Web/src/types/asset.ts
  Web/src/types/event.ts
  Web/src/types/leaderboard.ts
  Web/src/types/quiz.ts
Labels: enhancement

#34 Fixed AR multi-tracking issue
  Unity/ARmazing/Assets/_PROJECT/Prefab/AR_Canvas.prefab
  Unity/ARmazing/Assets/_PROJECT/Scenes/AR.unity
  Unity/ARmazing/Assets/_PROJECT/Script/ARManager.cs
  Unity/ARmazing/Assets/_PROJECT/Script/JoinEventManager.cs
  Unity/ARmazing/Assets/_PROJECT/Script/QuizButtonBehaviour.cs
  Unity/ARmazing/Assets/_PROJECT/Script/QuizManager.cs
  Unity/ARmazing/ProjectSettings/ProjectSettings.asset
  Unity/ARmazing/UserSettings/EditorUserSettings.asset
  Unity/ARmazing/UserSettings/Layouts/default-2021.dwlt
Labels: bug

#35 Create Quiz using JSON data
  Unity/ARmazing/Assets/JsonDotNet.meta
  Unity/ARmazing/Assets/JsonDotNet/Assemblies.meta
  Unity/ARmazing/Assets/JsonDotNet/Assemblies/AOT.meta
  Unity/ARmazing/Assets/JsonDotNet/Assemblies/AOT/Newtonsoft.Json.XML
  Unity/ARmazing/Assets/JsonDotNet/Assemblies/AOT/Newtonsoft.Json.XML.meta
  Unity/ARmazing/Assets/JsonDotNet/Assemblies/AOT/Newtonsoft.Json.dll
  Unity/ARmazing/Assets/JsonDotNet/Assemblies/AOT/Newtonsoft.Json.dll.meta
  Unity/ARmazing/Assets/JsonDotNet/Assemblies/Standalone.meta
  Unity/ARmazing/Assets/JsonDotNet/Assemblies/Standalone/Newtonsoft.Json.XML
  Unity/ARmazing/Assets/JsonDotNet/Assemblies/Standalone/Newtonsoft.Json.XML.meta
  Unity/ARmazing/Assets/JsonDotNet/Assemblies/Standalone/Newtonsoft.Json.dll
  Unity/ARmazing/Assets/JsonDotNet/Assemblies/Standalone/Newtonsoft.Json.dll.meta
  Unity/ARmazing/Assets/JsonDotNet/Assemblies/Windows.meta
  Unity/ARmazing/Assets/JsonDotNet/Assemblies/Windows/Newtonsoft.Json.XML
  Unity/ARmazing/Assets/JsonDotNet/Assemblies/Windows/Newtonsoft.Json.XML.meta
  Unity/ARmazing/Assets/JsonDotNet/Assemblies/Windows/Newtonsoft.Json.dll
  Unity/ARmazing/Assets/JsonDotNet/Assemblies/Windows/Newtonsoft.Json.dll.meta
  Unity/ARmazing/Assets/JsonDotNet/Documentation.meta
  Unity/ARmazing/Assets/JsonDotNet/Documentation/Json Net for Unity 2.0.1.pdf
  Unity/ARmazing/Assets/JsonDotNet/Documentation/Json Net for Unity 2.0.1.pdf.meta
  Unity/ARmazing/Assets/JsonDotNet/JsonDotNet201Source.zip
  Unity/ARmazing/Assets/JsonDotNet/JsonDotNet201Source.zip.meta
  Unity/ARmazing/Assets/JsonDotNet/link.xml
  Unity/ARmazing/Assets/JsonDotNet/link.xml.meta
  Unity/ARmazing/Assets/_PROJECT/Data/JSON.meta
  Unity/ARmazing/Assets/_PROJECT/Data/JSON/testquiz.json
  Unity/ARmazing/Assets/_PROJECT/Data/JSON/testquiz.json.meta
  Unity/ARmazing/Assets/_PROJECT/Script/QuestionAndAnswers.cs
  Unity/ARmazing/Assets/_PROJECT/Script/QuizManager.cs
  Unity/ARmazing/UserSettings/EditorUserSettings.asset
  Unity/ARmazing/UserSettings/Layouts/CurrentMaximizeLayout.dwlt
Labels: enhancement

#38 Fix: Authentication bug and added error page
  Web/src/components/Auth.tsx
  Web/src/components/UserProfile.tsx
  Web/src/pages/api/auth/[...nextauth].ts
  Web/src/pages/api/unity/quiz.ts
  Web/src/pages/callback/[callback]/index.tsx
  Web/src/pages/error.tsx
  Web/src/pages/verify-request.tsx
  Web/src/types/quiz.ts
Labels: bug, enhancement

#39 Create leaderboard scene UI and display ranking from JSON data
  Unity/ARmazing/Assets/_PROJECT/Data/JSON/testleaderboard.json
  Unity/ARmazing/Assets/_PROJECT/Data/JSON/testleaderboard.json.meta
  Unity/ARmazing/Assets/_PROJECT/Fonts/Title_Roboto-Black SDF.asset
  Unity/ARmazing/Assets/_PROJECT/Prefab/TeamRow.prefab
  Unity/ARmazing/Assets/_PROJECT/Prefab/TeamRow.prefab.meta
  Unity/ARmazing/Assets/_PROJECT/Scenes/Leaderboard.unity
  Unity/ARmazing/Assets/_PROJECT/Scenes/Leaderboard.unity.meta
  Unity/ARmazing/Assets/_PROJECT/Scenes/Quiz.unity
  Unity/ARmazing/Assets/_PROJECT/Script/LeaderboardManager.cs
  Unity/ARmazing/Assets/_PROJECT/Script/LeaderboardManager.cs.meta
  Unity/ARmazing/Assets/_PROJECT/Script/QuestionAndAnswers.cs
  Unity/ARmazing/Assets/_PROJECT/Script/QuizManager.cs
  Unity/ARmazing/UserSettings/EditorUserSettings.asset
  Unity/ARmazing/UserSettings/Layouts/default-2021.dwlt
Labels: enhancement

#43 Enabled strictNullChecks, Added Nextjs-Jest
  .github/workflows/build.yml
  Web/_tests_/common.test.ts
  Web/jest.config.js
  Web/package-lock.json
  Web/package.json
  Web/src/components/Auth.tsx
  Web/src/components/LoadingModal.tsx
  Web/src/components/Map.tsx
  Web/src/components/TableWidget.tsx
  Web/src/constants/date.ts
  Web/src/helper/dashboard.ts
  Web/src/helper/leaderboard.ts
  Web/src/helper/session.ts
  Web/src/pages/404.tsx
  Web/src/pages/_app.tsx
  Web/src/pages/api/asset/create.ts
  Web/src/pages/api/asset/edit.ts
  Web/src/pages/api/event/fetch.ts
  Web/src/pages/api/unity/asset.ts
  Web/src/pages/api/unity/event.ts
  Web/src/pages/api/unity/join.ts
  Web/src/pages/api/unity/leaderboard.ts
  Web/src/pages/api/unity/points.ts
  Web/src/pages/api/unity/quiz.ts
  Web/src/pages/asset.tsx
  Web/src/pages/callback/[callback]/index.tsx
  Web/src/pages/event.tsx
  Web/src/pages/index.tsx
  Web/src/pages/leaderboard.tsx
  Web/src/pages/quiz.tsx
  Web/src/pages/signin.tsx
  Web/src/types/next-auth.d.ts
  Web/tsconfig.json
Labels: enhancement

#47 Bug Fixes + Asset image change
  .github/workflows/build.yml
  Web/.husky/pre-commit
  Web/package-lock.json
  Web/package.json
  Web/public/assets/cl4b9auoo0018icdrn9aq2t8a_keviibear.png
  Web/public/assets/cl4raa6to0107ccdr3wbgb0ld_keviibear.png
  Web/src/constants/nextAuthOptions.ts
  Web/src/helper/leaderboard.ts
  Web/src/helper/quiz.ts
  Web/src/helper/session.ts
  Web/src/helper/sessionServer.ts
  Web/src/pages/api/asset/create.ts
  Web/src/pages/api/asset/delete.ts
  Web/src/pages/api/asset/edit.ts
  Web/src/pages/api/asset/fetch.ts
  Web/src/pages/api/auth/[...nextauth].ts
  Web/src/pages/api/dashboard/statistic.ts
  Web/src/pages/api/event/create.ts
  Web/src/pages/api/event/delete.ts
  Web/src/pages/api/event/edit.ts
  Web/src/pages/api/event/fetch.ts
  Web/src/pages/api/leaderboard/delete.ts
  Web/src/pages/api/leaderboard/fetch.ts
  Web/src/pages/api/leaderboard/reset.ts
  Web/src/pages/api/quiz/create.ts
  Web/src/pages/api/quiz/delete.ts
  Web/src/pages/api/quiz/edit.ts
  Web/src/pages/api/quiz/fetch.ts
  Web/src/pages/api/unity/asset.ts
  Web/src/pages/api/unity/event.ts
  Web/src/pages/api/unity/join.ts
  Web/src/pages/api/unity/leaderboard.ts
  Web/src/pages/api/unity/points.ts
  Web/src/pages/api/unity/quiz.ts
  Web/src/pages/asset.tsx
  Web/src/pages/event.tsx
  Web/src/pages/quiz.tsx
  Web/src/pages/verify-request.tsx
  Web/src/types/asset.ts
  Web/src/types/event.ts
  Web/src/types/leaderboard.ts
  Web/src/types/quiz.ts
Labels: enhancement
