Repository Orbital-ARMazing/Orbital-ARMazing, pull requests merged in 2022-07, with the labels that each got.

#52 Event Code generation and changes to Join Event API
  Web/prisma/schema.prisma
  Web/src/helper/event.ts
  Web/src/helper/leaderboard.ts
  Web/src/pages/api/asset/create.ts
  Web/src/pages/api/asset/delete.ts
  Web/src/pages/api/asset/edit.ts
  Web/src/pages/api/asset/fetch.ts
  Web/src/pages/api/dashboard/statistic.ts
  Web/src/pages/api/event/create.ts
  Web/src/pages/api/event/delete.ts
  Web/src/pages/api/event/edit.ts
  Web/src/pages/api/event/fetch.ts
  Web/src/pages/api/leaderboard/delete.ts
  Web/src/pages/api/leaderboard/fetch.ts
  Web/src/pages/api/leaderboard/reset.ts
  Web/src/pages/api/quiz/create.ts
  Web/src/pages/api/quiz/delete.ts
  Web/src/pages/api/quiz/edit.ts
  Web/src/pages/api/quiz/fetch.ts
  Web/src/pages/api/unity/asset.ts
  Web/src/pages/api/unity/event.ts
  Web/src/pages/api/unity/join.ts
  Web/src/pages/api/unity/leaderboard.ts
  Web/src/pages/api/unity/points.ts
  Web/src/pages/api/unity/quiz.ts
  Web/src/pages/asset.tsx
  Web/src/pages/event.tsx
  Web/src/types/event.ts
Labels: enhancement

#53 Logging
  Web/prisma/schema.prisma
  Web/src/constants/nextAuthOptions.ts
  Web/src/helper/asset.ts
  Web/src/helper/event.ts
  Web/src/helper/leaderboard.ts
  Web/src/helper/log.ts
  Web/src/helper/quiz.ts
  Web/src/pages/api/asset/delete.ts
  Web/src/pages/api/asset/edit.ts
  Web/src/pages/api/event/create.ts
  Web/src/pages/api/event/delete.ts
  Web/src/pages/api/event/edit.ts
  Web/src/pages/api/leaderboard/delete.ts
  Web/src/pages/api/leaderboard/reset.ts
  Web/src/pages/api/quiz/delete.ts
  Web/src/pages/api/quiz/edit.ts
  Web/src/pages/api/unity/points.ts
  Web/src/pages/leaderboard.tsx
  Web/src/types/log.ts
Labels: enhancement

#55 Edited Join Event API result
  Web/.eslintrc.json
  Web/src/pages/api/unity/join.ts
  Web/src/pages/verify-request.tsx
Labels: enhancement

#58 Leaderboard updates using downloaded data from API call
  Unity/ARmazing/Assets/_PROJECT/Scenes/Leaderboard.unity
  Unity/ARmazing/Assets/_PROJECT/Script/LeaderboardManager.cs
  Unity/ARmazing/UserSettings/EditorUserSettings.asset
  Unity/ARmazing/UserSettings/Layouts/default-2021.dwlt
Labels: enhancement

#59 Implemented creation of Quiz using downloaded data from API call
  Unity/ARmazing/Assets/_PROJECT/Scenes/AR.unity
  Unity/ARmazing/Assets/_PROJECT/Script/JoinEventManager.cs
  Unity/ARmazing/Assets/_PROJECT/Script/LeaderboardManager.cs
  Unity/ARmazing/Assets/_PROJECT/Script/QuizManager.cs
  Unity/ARmazing/UserSettings/EditorUserSettings.asset
  Unity/ARmazing/UserSettings/Layouts/default-2021.dwlt
Labels: enhancement

#60 Enhanced logging and new Attempt
  Web/prisma/schema.prisma
  Web/src/components/PlayerModal.tsx
  Web/src/helper/asset.ts
  Web/src/helper/attempt.ts
  Web/src/helper/dashboard.ts
  Web/src/helper/leaderboard.ts
  Web/src/helper/quiz.ts
  Web/src/pages/api/attempt/fetch.ts
  Web/src/pages/api/unity/leaderboard.ts
  Web/src/pages/api/unity/points.ts
  Web/src/pages/index.tsx
  Web/src/pages/leaderboard.tsx
  Web/src/types/attempt.ts
  Web/src/types/dashboard.ts
  Web/src/types/leaderboard.ts
Labels: enhancement

#61 User Permission API and improvements
  Web/_tests_/common.test.ts
  Web/src/components/PlayerModal.tsx
  Web/src/components/Sidebar.tsx
  Web/src/helper/asset.ts
  Web/src/helper/attempt.ts
  Web/src/helper/common.ts
  Web/src/helper/dashboard.ts
  Web/src/helper/event.ts
  Web/src/helper/leaderboard.ts
  Web/src/helper/permission.ts
  Web/src/helper/quiz.ts
  Web/src/helper/user.ts
  Web/src/pages/api/unity/points.ts
  Web/src/pages/api/user/edit.ts
  Web/src/pages/api/user/fetch.ts
  Web/src/pages/user.tsx
  Web/src/types/user.ts
Labels: enhancement

#63 Added mock session tests and LoadingModal for all essential pages
  Web/_tests_/__snapshots__/index.test.tsx.snap
  Web/_tests_/index.test.tsx
  Web/package-lock.json
  Web/package.json
  Web/src/components/Auth.tsx
  Web/src/components/Sidebar.tsx
  Web/src/components/UserProfile.tsx
  Web/src/helper/common.ts
  Web/src/pages/asset.tsx
  Web/src/pages/event.tsx
  Web/src/pages/index.tsx
  Web/src/pages/leaderboard.tsx
  Web/src/pages/quiz.tsx
  Web/src/pages/signin.tsx
  Web/src/pages/user.tsx
Labels: enhancement

#64 Update ar image tracking library using downloaded images from api call
  Unity/ARmazing/Assets/_PROJECT/Data/DefaultLibrary.asset
  Unity/ARmazing/Assets/_PROJECT/Scenes/AR.unity
  Unity/ARmazing/Assets/_PROJECT/Script/DynamicLibrary.cs
  Unity/ARmazing/Assets/_PROJECT/Script/JoinEventManager.cs
  Unity/ARmazing/Assets/_PROJECT/Script/QuizManager.cs
  Unity/ARmazing/ProjectSettings/ProjectSettings.asset
  Unity/ARmazing/UserSettings/EditorUserSettings.asset
  Unity/ARmazing/UserSettings/Layouts/default-2021.dwlt
Labels: enhancement

#66 Fixed issue with session not containing information
  Web/src/components/Auth.tsx
  Web/src/constants/nextAuthOptions.ts
  Web/src/helper/session.ts
  Web/src/helper/sessionServer.ts
  Web/src/pages/asset.tsx
  Web/src/pages/event.tsx
  Web/src/pages/quiz.tsx
Labels: bug

#69 Implemented full quiz functionality
  Unity/ARmazing/Assets/_PROJECT/Prefab/AR_Canvas.prefab
  Unity/ARmazing/Assets/_PROJECT/Scenes/AR.unity
  Unity/ARmazing/Assets/_PROJECT/Script/ARManager.cs
  Unity/ARmazing/Assets/_PROJECT/Script/ARManagerTest.cs
  Unity/ARmazing/Assets/_PROJECT/Script/ARManagerTest.cs.meta
  Unity/ARmazing/Assets/_PROJECT/Script/AnswerButtonBehaviour.cs
  Unity/ARmazing/Assets/_PROJECT/Script/BackButtonBehaviour.cs
  Unity/ARmazing/Assets/_PROJECT/Script/DynamicLibrary.cs
  Unity/ARmazing/Assets/_PROJECT/Script/JoinEventManager.cs
  Unity/ARmazing/Assets/_PROJECT/Script/LeaderboardManager.cs
  Unity/ARmazing/Assets/_PROJECT/Script/QuizButtonBehaviour.cs
  Unity/ARmazing/Assets/_PROJECT/Script/QuizManager.cs
  Unity/ARmazing/ProjectSettings/ProjectSettings.asset
  Unity/ARmazing/ProjectSettings/TagManager.asset
  Unity/ARmazing/UserSettings/EditorUserSettings.asset
  Unity/ARmazing/UserSettings/Layouts/default-2021.dwlt
Labels: enhancement

#72 Minor changes to logic flow for Points API Route
  Web/src/pages/api/unity/join.ts
  Web/src/pages/api/unity/landmark.ts
  Web/src/pages/api/unity/points.ts
  Web/src/pages/quiz.tsx
  Web/src/types/asset.ts
Labels: bug, enhancement

#73 Filter out assets by event for Quiz
  Web/src/pages/asset.tsx
  Web/src/pages/quiz.tsx
Labels: enhancement

#74 Added reminder message
  Web/src/components/Auth.tsx
  Web/src/helper/session.ts
  Web/src/helper/sessionServer.ts
  Web/src/pages/verify-request.tsx
Labels: documentation

#75 Write documentation for unity application code
  Unity/ARmazing/Assets/_PROJECT/Scenes/Quiz.unity
  Unity/ARmazing/Assets/_PROJECT/Script/ARManager.cs
  Unity/ARmazing/Assets/_PROJECT/Script/AnswerButtonBehaviour.cs
  Unity/ARmazing/Assets/_PROJECT/Script/BackButtonBehaviour.cs
  Unity/ARmazing/Assets/_PROJECT/Script/DynamicLibrary.cs
  Unity/ARmazing/Assets/_PROJECT/Script/JoinEventManager.cs
  Unity/ARmazing/Assets/_PROJECT/Script/LandmarkManager.cs
  Unity/ARmazing/Assets/_PROJECT/Script/LandmarksButtonBehaviour.cs
  Unity/ARmazing/Assets/_PROJECT/Script/LeaderboardButtonBehaviour.cs
  Unity/ARmazing/Assets/_PROJECT/Script/LeaderboardManager.cs
  Unity/ARmazing/Assets/_PROJECT/Script/QuizButtonBehaviour.cs
  Unity/ARmazing/Assets/_PROJECT/Script/QuizManager.cs
  Unity/ARmazing/ProjectSettings/ProjectSettings.asset
  Unity/ARmazing/UserSettings/EditorUserSettings.asset
  Unity/ARmazing/UserSettings/Layouts/default-2021.dwlt
Labels: documentation
